#:schema node_modules/wrangler/config-schema.json
name = "sub"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "652c3210db68412498351c28b613139c" }
]

[assets]
directory = "./public"
